# flask-backend/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-backend.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "flask-backend.name" . }}
